
FRAMESPERSEC = 60
SCREENWIDTH = 1000
SCREENHEIGHT = 700
ARENAWIDTH = SCREENWIDTH
ARENAHEIGHT = 597
PLAYER_R = 40
CHAIN = 10

ARENAHEIGHT_Q = ARENAHEIGHT - PLAYER_R - CHAIN
ARENAWIDTH_Q = ARENAWIDTH - PLAYER_R

KROK = 6
